name: CI

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Create setting.xml
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          repositories: '[{ "id": "releases", "url": "${ARTIFACTORY_HOST}/libs-release" }, { "id": "snapshots", "url": "${ARTIFACTORY_HOST}/libs-snapshot" }]'
          servers: '[{ "id": "releases", "username": "${ARTIFACTORY_USERNAME}", "password": "${ARTIFACTORY_PASSWORD}" }, { "id": "snapshots", "username": "${ARTIFACTORY_USERNAME}", "password": "${ARTIFACTORY_PASSWORD}" }]'
      - name: Build with Maven
        run: mvn -B clean package deploy
        env:
          ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
          ARTIFACTORY_HOST: ${{ secrets.ARTIFACTORY_HOST }}
