name: Maven release

on:
  workflow_dispatch:
    inputs:
      description:
        description: 'Description'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Create setting.xml
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          repositories: '[{ "id": "releases", "url": "${ARTIFACTORY_HOST}/libs-release" }, { "id": "snapshots", "url": "${ARTIFACTORY_HOST}/libs-snapshot" }]'
          servers: '[{ "id": "releases", "username": "${ARTIFACTORY_USERNAME}", "password": "${ARTIFACTORY_PASSWORD}" }, { "id": "snapshots", "username": "${ARTIFACTORY_USERNAME}", "password": "${ARTIFACTORY_PASSWORD}" }]'
      - name: Configure Git User
        run: |
          git config user.email "release@github.com"
          git config user.name "GitHub Release Action"
      - name: Release:prepare
        run: mvn -B release:prepare release:perform -Darguments="-Dmaven.javadoc.skip=true"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ARTIFACTORY_HOST: ${{ secrets.ARTIFACTORY_HOST }}
          ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
